"""Private S3-compatible object storage. Keys are generated by the backend."""
import os
import boto3
from botocore.config import Config

class ObjectStore:
    def __init__(self):
        self.bucket = os.getenv('S3_BUCKET','hyper-sources')
        self.client = boto3.client('s3',
            endpoint_url=os.getenv('S3_ENDPOINT_URL') or None,
            region_name=os.getenv('AWS_REGION','us-east-1'),
            config=Config(signature_version='s3v4',connect_timeout=5,read_timeout=30,
                          retries={'max_attempts':2},s3={'addressing_style':os.getenv('S3_ADDRESSING_STYLE','path')}))

    def put(self, key, body, content_type):
        self.client.put_object(Bucket=self.bucket,Key=key,Body=body,ContentType=content_type)

    def read(self, key):
        result = self.client.get_object(Bucket=self.bucket,Key=key)
        try:
            return result['Body'].read()
        finally:
            result['Body'].close()

    def check(self):
        self.client.head_bucket(Bucket=self.bucket)
