import initialize0 from "./runtime/math-and-assets.js";
import initialize1 from "./runtime/viewport-state.js";
import initialize2 from "./runtime/projects-data.js";
import initialize3 from "./runtime/archive-data.js";
import initialize4 from "./runtime/asset-loader.js";
import initialize5 from "./runtime/animation-loop.js";
import initialize6 from "./runtime/color-theme.js";
import initialize7 from "./runtime/page-lifecycle.js";
import initialize8 from "./runtime/splash.js";
import initialize9 from "./runtime/pointer.js";
import initialize10 from "./runtime/design.js";
import initialize11 from "./runtime/actions.js";
import initialize12 from "./runtime/reserved.js";
import initialize13 from "./runtime/page-transition.js";
import initialize14 from "./runtime/navigation.js";
import initialize15 from "./runtime/navigation-hooks.js";
import initialize16 from "./runtime/navigation-actions.js";
import initialize17 from "./runtime/project-events.js";
import initialize18 from "./runtime/language.js";
import initialize19 from "./runtime/text-area.js";
import initialize20 from "./runtime/slider.js";
import initialize21 from "./runtime/accordion.js";
import initialize22 from "./runtime/reserved-ui.js";
import initialize23 from "./runtime/inview.js";
import initialize24 from "./runtime/menu.js";
import initialize25 from "./runtime/project-titles.js";
import initialize26 from "./runtime/mail.js";
import initialize27 from "./runtime/css-lifecycle.js";
import initialize28 from "./runtime/video.js";
import initialize29 from "./runtime/project-scroll.js";
import initialize30 from "./runtime/content-scroll.js";
import initialize31 from "./runtime/renderer.js";
import initialize32 from "./runtime/project-wall.js";
import initialize33 from "./runtime/reflective-floor.js";
import initialize34 from "./runtime/lights.js";
import initialize35 from "./runtime/particles.js";
import initialize36 from "./runtime/fog.js";
import initialize37 from "./runtime/logo.js";
import initialize38 from "./runtime/archive-scene.js";
import initialize39 from "./runtime/content-surfaces.js";
import initialize40 from "./runtime/pointer-texture.js";
import initialize41 from "./runtime/interface-icons.js";
import initialize42 from "./runtime/scene-coordinator.js";
import initialize43 from "./runtime/cameras.js";
import initialize44 from "./runtime/scene-first.js";
import initialize45 from "./runtime/scene-reflection.js";
import initialize46 from "./runtime/scene-compositor.js";
import initialize47 from "./runtime/scene-output.js";
import initialize48 from "./runtime/scene-noise.js";
export default function initializeDesktop() {
  initialize0();
  initialize1();
  initialize2();
  initialize3();
  initialize4();
  initialize5();
  initialize6();
  initialize7();
  initialize8();
  initialize9();
  initialize10();
  initialize11();
  initialize12();
  initialize13();
  initialize14();
  initialize15();
  initialize16();
  initialize17();
  initialize18();
  initialize19();
  initialize20();
  initialize21();
  initialize22();
  initialize23();
  initialize24();
  initialize25();
  initialize26();
  initialize27();
  initialize28();
  initialize29();
  initialize30();
  initialize31();
  initialize32();
  initialize33();
  initialize34();
  initialize35();
  initialize36();
  initialize37();
  initialize38();
  initialize39();
  initialize40();
  initialize41();
  initialize42();
  initialize43();
  initialize44();
  initialize45();
  initialize46();
  initialize47();
  initialize48();
}
